pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ArjunKalirana/devops.git'
            }
        }

        stage("Install Dependencies") {
            steps {
                sh 'npm install'
            }
        }

        stage("Run Tests") {
            steps {
                echo "No tests added yet"
            }
        }

        stage("Build Docker Image") {
            steps {
                sh 'docker build -t devops-app .'
            }
        }

    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
    }
}
